//
// GalleryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GalleryItem: Sendable, Codable, ParameterConvertible, Hashable {

    /** Gallery item Identifier */
    public var id: Int
    public var locale: SupportedLocale?
    /** Comment on this item */
    public var tweet: String?
    /** Image identifier */
    public var image: String
    /** Item creation time in ISO format */
    public var created: Date
    /** Alternative text describing image */
    public var alt: String
    /** Whether to not display this item in the gallery */
    public var trashed: Bool

    public init(id: Int, locale: SupportedLocale?, tweet: String?, image: String, created: Date, alt: String, trashed: Bool) {
        self.id = id
        self.locale = locale
        self.tweet = tweet
        self.image = image
        self.created = created
        self.alt = alt
        self.trashed = trashed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case locale
        case tweet
        case image
        case created
        case alt
        case trashed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(locale, forKey: .locale)
        try container.encode(tweet, forKey: .tweet)
        try container.encode(image, forKey: .image)
        try container.encode(created, forKey: .created)
        try container.encode(alt, forKey: .alt)
        try container.encode(trashed, forKey: .trashed)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GalleryItem: Identifiable {}
