//
// GalleryPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GalleryPutRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Target locale, null if global */
    public var locale: String?
    /** Comment on this item */
    public var tweet: String?
    /** Image identifier */
    public var imageId: Int

    public init(locale: String?, tweet: String?, imageId: Int) {
        self.locale = locale
        self.tweet = tweet
        self.imageId = imageId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case tweet
        case imageId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locale, forKey: .locale)
        try container.encode(tweet, forKey: .tweet)
        try container.encode(imageId, forKey: .imageId)
    }
}

