//
// GalleryIdPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GalleryIdPatchRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var locale: SupportedLocale?
    public var tweet: String?
    public var imageId: Int?
    public var trashed: Bool?

    public init(locale: SupportedLocale? = nil, tweet: String? = nil, imageId: Int? = nil, trashed: Bool? = nil) {
        self.locale = locale
        self.tweet = tweet
        self.imageId = imageId
        self.trashed = trashed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case tweet
        case imageId
        case trashed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(tweet, forKey: .tweet)
        try container.encodeIfPresent(imageId, forKey: .imageId)
        try container.encodeIfPresent(trashed, forKey: .trashed)
    }
}

