//
// ImagePost201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImagePost201Response: Sendable, Codable, Hashable {

    /** Image identifier in plain text */
    public var id: Int
    /** Publicly accessible image URL */
    public var url: String

    public init(id: Int, url: String) {
        self.id = id
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(url, forKey: .url)
    }
}


extension ImagePost201Response: Identifiable {}
