//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Image: Sendable, Codable, ParameterConvertible, Hashable {

    /** Image identifier */
    public var id: Int
    /** Publicly accessible URL */
    public var url: String
    /** Alernative text describing the image content */
    public var alt: String

    public init(id: Int, url: String, alt: String) {
        self.id = id
        self.url = url
        self.alt = alt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case alt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(url, forKey: .url)
        try container.encode(alt, forKey: .alt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Image: Identifiable {}
