//
// ImagePutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImagePutRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** CDN URL, publicly accessible */
    public var url: String
    /** Alernative text describing the image */
    public var alt: String

    public init(url: String, alt: String) {
        self.url = url
        self.alt = alt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case alt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(alt, forKey: .alt)
    }
}

