//
// Shape.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum Shape: String, Sendable, Codable, CaseIterable {
    case clover = "clover"
    case elevensidedstar = "elevenSidedStar"
    case sixsidedstar = "sixSidedStar"
    case tiltedoval = "tiltedOval"
    case tiltedpentagon = "tiltedPentagon"
    case tiltedrectangle = "tiltedRectangle"
}
