//
// StringsByLocaleGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StringsByLocaleGet200Response: Sendable, Codable, Hashable {

    public var en: [String]
    public var zh: [String]
    public var zhTw: [String]

    public init(en: [String], zh: [String], zhTw: [String]) {
        self.en = en
        self.zh = zh
        self.zhTw = zhTw
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case en
        case zh
        case zhTw = "zh-tw"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(en, forKey: .en)
        try container.encode(zh, forKey: .zh)
        try container.encode(zhTw, forKey: .zhTw)
    }
}

