//
// SupportedLocale.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SupportedLocale: String, Sendable, Codable, CaseIterable {
    case en = "en"
    case zh = "zh"
    case zhTw = "zh-tw"
}
