//
// UpdatePost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdatePost: Sendable, Codable, ParameterConvertible, Hashable {

    /** Reference ID */
    public var id: Int
    /** ISO format time representation */
    public var created: Date
    /** Leading header text, in bold color and monospace font */
    public var header: String
    /** Title text in Futura font */
    public var title: String
    /** Tweet content in system Sans font */
    public var summary: String
    /** Shape of the mask */
    public var mask: Shape
    /** Target locale of the post */
    public var locale: SupportedLocale
    /** Whether to not display this post */
    public var trashed: Bool
    public var cover: UpdatePostCover?

    public init(id: Int, created: Date, header: String, title: String, summary: String, mask: Shape, locale: SupportedLocale, trashed: Bool, cover: UpdatePostCover?) {
        self.id = id
        self.created = created
        self.header = header
        self.title = title
        self.summary = summary
        self.mask = mask
        self.locale = locale
        self.trashed = trashed
        self.cover = cover
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case created
        case header
        case title
        case summary
        case mask
        case locale
        case trashed
        case cover
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(created, forKey: .created)
        try container.encode(header, forKey: .header)
        try container.encode(title, forKey: .title)
        try container.encode(summary, forKey: .summary)
        try container.encode(mask, forKey: .mask)
        try container.encode(locale, forKey: .locale)
        try container.encode(trashed, forKey: .trashed)
        try container.encode(cover, forKey: .cover)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UpdatePost: Identifiable {}
