//
// UpdateIdPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateIdPatchRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Target locale of this post */
    public var locale: SupportedLocale?
    /** Top header of the card */
    public var header: String?
    public var title: String?
    public var summary: String?
    /** Image identifier */
    public var cover: Int?
    public var mask: Shape?
    public var trashed: Bool?

    public init(locale: SupportedLocale? = nil, header: String? = nil, title: String? = nil, summary: String? = nil, cover: Int? = nil, mask: Shape? = nil, trashed: Bool? = nil) {
        self.locale = locale
        self.header = header
        self.title = title
        self.summary = summary
        self.cover = cover
        self.mask = mask
        self.trashed = trashed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case header
        case title
        case summary
        case cover
        case mask
        case trashed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(header, forKey: .header)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(cover, forKey: .cover)
        try container.encodeIfPresent(mask, forKey: .mask)
        try container.encodeIfPresent(trashed, forKey: .trashed)
    }
}

