//
// UpdatePostCover.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdatePostCover: Sendable, Codable, Hashable {

    /** Image URL */
    public var image: String
    /** Alternative text */
    public var alt: String
    /** Image identifier */
    public var id: Int

    public init(image: String, alt: String, id: Int) {
        self.image = image
        self.alt = alt
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case alt
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(alt, forKey: .alt)
        try container.encode(id, forKey: .id)
    }
}


extension UpdatePostCover: Identifiable {}
