//
// UpdatePostCover.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdatePostCover: Sendable, Codable, ParameterConvertible, Hashable {

    /** Image URL */
    public var image: String
    /** Alternative text */
    public var alt: String

    public init(image: String, alt: String) {
        self.image = image
        self.alt = alt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case alt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(alt, forKey: .alt)
    }
}

