//
// UpdatePutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdatePutRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Target locale of this post */
    public var locale: SupportedLocale
    /** Top header of the card, in bold color and monospaced font */
    public var header: String
    /** Title in Futura font */
    public var title: String
    /** Tweet in Sans font */
    public var summary: String
    /** Cover image identifier */
    public var cover: Int?
    /** Mask to the cover image */
    public var mask: Shape

    public init(locale: SupportedLocale, header: String, title: String, summary: String, cover: Int? = nil, mask: Shape) {
        self.locale = locale
        self.header = header
        self.title = title
        self.summary = summary
        self.cover = cover
        self.mask = mask
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case header
        case title
        case summary
        case cover
        case mask
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locale, forKey: .locale)
        try container.encode(header, forKey: .header)
        try container.encode(title, forKey: .title)
        try container.encode(summary, forKey: .summary)
        try container.encodeIfPresent(cover, forKey: .cover)
        try container.encode(mask, forKey: .mask)
    }
}

